### ISSUE TITLE
Please add just a tiny bit more description (and preferably a readme to the github)

### ISSUE THREAD

**Issue by tiggerbiggo** [CataratasDolly/Infinity-Rooms#2]
Not everyone knows what an "infinity room" is, and this repo has no readme.md for a description either.

I was confused when one of the players on my server was trying to get me to install this, it's a great looking mod but I couldn't work out for the life of me what the heck it even does, and looking at the source code confused me a lot until I realised this mod doesn't make actual infinite rooms. I didn't want to install a mod that adds more dimensions as we're already having lag problems, hence why I had to check the source code as I didn't know, and hence the confusion.

Please explain that this adds blocks that make it LOOK like you're in an infinite space, otherwise it just sounds like it can make actual infinite rooms with these blocks somehow. The description is really short and doesn't really explain what the mod does at all unless you already know what an infinity room is.

### Proposed description:

Infinity Rooms adds blocks that allow you to quickly create infinity rooms without the use of maps.
These blocks are a single solid colour, are always fully lit and show no outline, creating the illusion of an infinite space if you make a room out of them. There are also functional variants of these blocks, listed in the features below;

Features
* Solid Blocks
* Doors
* Trapdoors
* Buttons

Thanks :)

**Comment by CataratasDolly** [comment]
Thanks for the suggestion, I thought the description was clear already.
